### ISSUE TITLE
Missing play_sd_wav.h

### ISSUE THREAD

**Issue by alexsteffens** [MGS1/Wedding-Audio-Guestbook---Teensy-4#1]
https://github.com/MGS1/Wedding-Audio-Guestbook---Teensy-4/blob/a0c030d61822cda36ffd3bd537b1d076750136cf/Audio-Guestbook.ino#L23

I am not sure if this file is mandatory. But it is included in the existing code and not present in the repository.

If you have time to upload more details about the hardware part, I would be very grateful. Unfortunately, I am very inexperienced there. Thank you so much 

Edit: I  should have checked the original repository (https://github.com/playfultechnology/audio-guestbook) first. There you can find the missing file. Sorry!

**Comment by MGS1** [comment]
Hey nice catch I can update this when I have time. I just got bored with the project. Thanks!Sent from my iPhoneOn Aug 16, 2023, at 7:56 AM, Alexander Steffens ***@***.***> wrote:﻿
Closed #1 as completed.
